name = "InverseGaussTransform"
uuid = "31b5ff0a-e5dd-4c82-89e7-48e4b15b52c0"
authors = ["Patrick Eastham <peastham@math.fsu.edu> and contributors"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StokesParticles = "1705063e-ae85-4622-8975-eebdf1f90980"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
